# Generated by Django 2.0.2 on 2018-02-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='is_supported',
            field=models.BooleanField(default=False, verbose_name='supported'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Country', verbose_name='country'),
        ),
        migrations.AlterField(
            model_name='district',
            name='is_supported',
            field=models.BooleanField(default=False, verbose_name='supported'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='district',
            name='suffix',
            field=models.CharField(blank=True, max_length=50, verbose_name='suffix'),
        ),
    ]
