# Generated by Django 2.0.3 on 2018-03-27 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20180212_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': '国・地域', 'verbose_name_plural': '国・地域'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': '行政区画', 'verbose_name_plural': '行政区画'},
        ),
        migrations.AlterField(
            model_name='country',
            name='is_supported',
            field=models.BooleanField(default=False, verbose_name='対応'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=50, verbose_name='国・地域名'),
        ),
        migrations.AlterField(
            model_name='district',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Country', verbose_name='国・地域ID'),
        ),
        migrations.AlterField(
            model_name='district',
            name='is_supported',
            field=models.BooleanField(default=False, verbose_name='対応'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=50, verbose_name='行政区画名'),
        ),
        migrations.AlterField(
            model_name='district',
            name='suffix',
            field=models.CharField(blank=True, max_length=50, verbose_name='接尾語'),
        ),
    ]
