# Generated by Django 2.0.2 on 2018-02-12 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20180212_1716'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(blank=True, verbose_name='price request')),
                ('postage', models.IntegerField(default=0, verbose_name='postage')),
                ('arriving_at', models.DateTimeField(verbose_name='arriving at')),
            ],
            options={
                'verbose_name': 'agreement',
                'verbose_name_plural': 'agreements',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('delivery_method', models.SmallIntegerField(verbose_name='delivery request')),
                ('payment_method', models.SmallIntegerField(verbose_name='payment request')),
                ('price_request', models.IntegerField(blank=True, verbose_name='price request')),
                ('hand_place', models.CharField(blank=True, max_length=255, verbose_name='hand place request')),
                ('status', models.SmallIntegerField(default=0, verbose_name='status')),
                ('expired_at', models.DateTimeField(blank=True, verbose_name='expired at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member', verbose_name='buyer')),
                ('buyer_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.MemberAddress', verbose_name="buyer's address")),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item', verbose_name='item')),
            ],
            options={
                'verbose_name': 'request',
                'verbose_name_plural': 'requests',
            },
        ),
        migrations.AddField(
            model_name='agreement',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.Request', verbose_name='request'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member', verbose_name='seller'),
        ),
        migrations.AddField(
            model_name='agreement',
            name='seller_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.MemberAddress', verbose_name="seller's address"),
        ),
    ]
