# Generated by Django 2.0.4 on 2018-04-12 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0019_auto_20180412_1727'),
        ('main', '0002_auto_20180327_1448'),
        ('transaction', '0002_auto_20180327_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='依頼タイトル')),
                ('description', models.TextField(blank=True, verbose_name='依頼説明文')),
                ('delivery_method', models.SmallIntegerField(verbose_name='配送方法')),
                ('payment_method', models.SmallIntegerField(verbose_name='支払方法')),
                ('price_order', models.IntegerField(blank=True, verbose_name='希望価格')),
                ('hand_place', models.CharField(blank=True, max_length=255, verbose_name='商品手渡し場所')),
                ('delivered_order', models.DateTimeField(blank=True, null=True, verbose_name='希望お届け日時')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状態')),
                ('expired_at', models.DateTimeField(blank=True, verbose_name='掲載終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item', verbose_name='商品ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID')),
                ('user_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserAddress', verbose_name='ユーザー住所ID')),
            ],
            options={
                'verbose_name': '依頼',
                'verbose_name_plural': '依頼',
            },
        ),
    ]
