# Generated by Django 2.0.4 on 2018-04-12 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='agreement',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transaction.Order', verbose_name='依頼ID'),
            preserve_default=False,
        ),
    ]
