# Generated by Django 2.0.4 on 2018-04-12 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_agreement_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='request',
        ),
    ]
