# Generated by Django 2.0.4 on 2018-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20180412_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.IntegerField(verbose_name='個数'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(verbose_name='ユニークID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='配送方法'),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, verbose_name='リクエスト説明文'),
        ),
        migrations.AlterField(
            model_name='order',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='掲載終了日'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='支払方法'),
        ),
        migrations.AlterField(
            model_name='order',
            name='price_order',
            field=models.IntegerField(blank=True, null=True, verbose_name='希望価格'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(default=1, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='order',
            name='title',
            field=models.CharField(blank=True, max_length=50, verbose_name='リクエストタイトル'),
        ),
    ]
