# Generated by Django 2.0.4 on 2018-04-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_auto_20180412_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='状態有効期限'),
        ),
    ]
