# Generated by Django 2.0.4 on 2018-04-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20180414_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='delivered_order',
            new_name='delivered_at_order',
        ),
    ]
