# Generated by Django 2.0.4 on 2018-04-14 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20180414_1622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreement',
            name='order',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='user',
        ),
        migrations.RemoveField(
            model_name='agreement',
            name='user_address',
        ),
        migrations.DeleteModel(
            name='Agreement',
        ),
    ]
