# Generated by Django 2.0.4 on 2018-04-16 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20180414_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='proposal',
        ),
    ]
