# Generated by Django 2.0.4 on 2018-04-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20180414_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_at_order',
            field=models.DateField(blank=True, null=True, verbose_name='希望お届け日時'),
        ),
    ]
