# Generated by Django 2.0.2 on 2018-02-12 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Facebook ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='kik_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='KIK ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='LINE ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, verbose_name='phone number'),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='WhatsApp ID'),
        ),
        migrations.AlterField(
            model_name='memberaddress',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='memberaddress',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
    ]
