# Generated by Django 2.0.2 on 2018-02-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20180212_1456'),
        ('accounts', '0002_auto_20180212_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriving_at', models.DateTimeField(verbose_name='arrival time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.Country', verbose_name='country')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.District', verbose_name='district')),
            ],
            options={
                'verbose_name': 'arrival',
                'verbose_name_plural': 'arrivals',
            },
        ),
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departing_at', models.DateTimeField(verbose_name='departure time')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.Country', verbose_name='country')),
                ('district', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.District', verbose_name='district')),
            ],
            options={
                'verbose_name': 'departure',
                'verbose_name_plural': 'departures',
            },
        ),
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Member', verbose_name='member')),
            ],
            options={
                'verbose_name': 'itinerary',
                'verbose_name_plural': 'itineraries',
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('arrival', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Arrival', verbose_name='arrival')),
                ('departure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Departure', verbose_name='departure')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Itinerary', verbose_name='itinerary')),
            ],
            options={
                'verbose_name': 'transfer',
                'verbose_name_plural': 'transfers',
            },
        ),
    ]
