# Generated by Django 2.0.2 on 2018-03-01 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_arrival_departure_itinerary_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='purpose',
            field=models.SmallIntegerField(default=0, verbose_name='purpose'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='member',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='member level'),
        ),
        migrations.AddField(
            model_name='member',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='WeChat ID'),
        ),
        migrations.AddField(
            model_name='transfer',
            name='ticket',
            field=models.SmallIntegerField(default=0, verbose_name='ticket'),
            preserve_default=False,
        ),
    ]
