# Generated by Django 2.0.2 on 2018-03-03 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180301_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='birthday',
            field=models.DateField(blank=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='member',
            name='jender',
            field=models.SmallIntegerField(blank=True, verbose_name='jender'),
        ),
    ]
