# Generated by Django 2.0.2 on 2018-03-03 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20180303_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_traveller',
            field=models.BooleanField(default=False, verbose_name='traveller'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='電話番号はハイフンを除いた半角数字で入力してください。', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
    ]
