# Generated by Django 2.0.2 on 2018-03-05 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20180305_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Facebook ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Instagram ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='kik_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='KIK ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='LINE ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Twitter ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='WeChat ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='WhatsApp ID'),
        ),
    ]
