# Generated by Django 2.0.2 on 2018-03-09 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meta', '0002_auto_20180212_1456'),
        ('accounts', '0013_auto_20180308_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=9, verbose_name='postal code')),
                ('address1', models.CharField(max_length=255, verbose_name='address1')),
                ('address2', models.CharField(blank=True, max_length=255, verbose_name='address2')),
                ('first_name', models.CharField(max_length=50, verbose_name='first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='last name')),
                ('is_default', models.BooleanField(default=False, verbose_name='default')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.District', verbose_name='district')),
            ],
            options={
                'verbose_name': "user's address",
                'verbose_name_plural': "user's addresses",
            },
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='facebook_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Facebook ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='instagram_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Instagram ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='banned'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_traveller',
            field=models.BooleanField(default=False, verbose_name='traveller'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='jender',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='jender'),
        ),
        migrations.AddField(
            model_name='user',
            name='kik_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='KIK ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='user level'),
        ),
        migrations.AddField(
            model_name='user',
            name='line_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='LINE ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='notice',
            field=models.BooleanField(default=False, verbose_name='notice'),
        ),
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=50, verbose_name='profession'),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Twitter ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='user',
            name='wechat_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='WeChat ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='WhatsApp ID'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
