# Generated by Django 2.0.2 on 2018-03-09 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20180309_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='member',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
