# Generated by Django 2.0.2 on 2018-03-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180309_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='social_confirm_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='social confirm deadline'),
        ),
    ]
