# Generated by Django 2.0.3 on 2018-03-27 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180309_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=255, verbose_name='フライトナンバー')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'フライト',
                'verbose_name_plural': 'フライト',
            },
        ),
        migrations.AlterModelOptions(
            name='arrival',
            options={'verbose_name': '到着', 'verbose_name_plural': '到着'},
        ),
        migrations.AlterModelOptions(
            name='departure',
            options={'verbose_name': '出発', 'verbose_name_plural': '出発'},
        ),
        migrations.AlterModelOptions(
            name='itinerary',
            options={'verbose_name': '旅程', 'verbose_name_plural': '旅程'},
        ),
        migrations.AlterModelOptions(
            name='transfer',
            options={'verbose_name': '移動', 'verbose_name_plural': '移動'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'ユーザー住所', 'verbose_name_plural': 'ユーザー住所'},
        ),
        migrations.AlterField(
            model_name='arrival',
            name='arriving_at',
            field=models.DateTimeField(verbose_name='到着日時'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.Country', verbose_name='国・地域ID'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.District', verbose_name='行政区画ID'),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='country',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.Country', verbose_name='国・地域ID'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='departing_at',
            field=models.DateTimeField(verbose_name='出発日時'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='district',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='meta.District', verbose_name='行政区画ID'),
        ),
        migrations.AlterField(
            model_name='departure',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='description',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='purpose',
            field=models.SmallIntegerField(verbose_name='目的'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='arrival',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Arrival', verbose_name='到着ID'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='departure',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Departure', verbose_name='出発ID'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='itinerary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Itinerary', verbose_name='旅程ID'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='ticket',
            field=models.SmallIntegerField(verbose_name='チケット取得状況'),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生年月日'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='メールアドレス認証'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False, verbose_name='アカウント凍結'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_traveller',
            field=models.BooleanField(default=False, verbose_name='トラベラーフラグ'),
        ),
        migrations.AlterField(
            model_name='user',
            name='jender',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.SmallIntegerField(default=1, verbose_name='ユーザーレベル'),
        ),
        migrations.AlterField(
            model_name='user',
            name='notice',
            field=models.BooleanField(default=False, verbose_name='配信の希望'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, max_length=50, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_confirm_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ソーシャルログイン確認期限'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='ユニークID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uuid_deadline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ユニークID有効期限'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address1',
            field=models.CharField(max_length=255, verbose_name='住所1'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address2',
            field=models.CharField(blank=True, max_length=255, verbose_name='住所2'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.District', verbose_name='行政区画ID'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='名'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='デフォルトフラグ'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='姓'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(max_length=9, verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AddField(
            model_name='flight',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Transfer', verbose_name='移動ID'),
        ),
    ]
