# Generated by Django 2.0.4 on 2018-04-14 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20180414_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='arrival',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='departure',
        ),
    ]
