# Generated by Django 2.0.4 on 2018-04-14 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20180414_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrival',
            name='country',
        ),
        migrations.RemoveField(
            model_name='arrival',
            name='district',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='country',
        ),
        migrations.RemoveField(
            model_name='departure',
            name='district',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='transfer',
        ),
        migrations.DeleteModel(
            name='Arrival',
        ),
        migrations.DeleteModel(
            name='Departure',
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
