# Generated by Django 2.0.4 on 2018-04-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180414_1745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='arrival_country',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='arrival_district',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='departure_country',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='departure_district',
        ),
        migrations.RemoveField(
            model_name='transfer',
            name='itinerary',
        ),
        migrations.DeleteModel(
            name='Transfer',
        ),
    ]
