# Generated by Django 2.0.4 on 2018-04-16 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20180416_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='user',
        ),
        migrations.DeleteModel(
            name='Itinerary',
        ),
    ]
