# Generated by Django 2.0.3 on 2018-03-27 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='価格')),
                ('quantity', models.IntegerField(verbose_name='商品数')),
                ('description', models.TextField(blank=True, verbose_name='説明文')),
                ('expired_at', models.DateTimeField(blank=True, verbose_name='掲載終了日')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '商品提案',
                'verbose_name_plural': '商品提案',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'カテゴリー', 'verbose_name_plural': 'カテゴリー'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': '商品画像', 'verbose_name_plural': '商品画像'},
        ),
        migrations.AlterModelOptions(
            name='itemlike',
            options={'verbose_name': 'いいね', 'verbose_name_plural': 'いいね'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'タグ', 'verbose_name_plural': 'タグ'},
        ),
        migrations.RemoveField(
            model_name='itemimage',
            name='image',
        ),
        migrations.AddField(
            model_name='itemimage',
            name='image_path',
            field=models.ImageField(default=0, unique=True, upload_to='images/', verbose_name='画像パス'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='カテゴリー名'),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='category',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(to='main.Category', verbose_name='カテゴリーID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meta.Country', verbose_name='国・地域ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True, verbose_name='商品説明文'),
        ),
        migrations.AlterField(
            model_name='item',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meta.District', verbose_name='行政区画ID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='商品名'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ManyToManyField(blank=True, to='main.Tag', verbose_name='タグID'),
        ),
        migrations.AlterField(
            model_name='item',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='item',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item', verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='itemlike',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='itemlike',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item', verbose_name='商品ID'),
        ),
        migrations.AlterField(
            model_name='itemlike',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='itemlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='作成日時'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='タグ名'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='status',
            field=models.SmallIntegerField(default=0, verbose_name='状態'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
        migrations.AddField(
            model_name='itemrecommendation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Item', verbose_name='商品ID'),
        ),
        migrations.AddField(
            model_name='itemrecommendation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザーID'),
        ),
    ]
