# Generated by Django 2.0.4 on 2018-04-26 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180327_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='recommendation_ranking',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='おすすめ順'),
        ),
        migrations.AddField(
            model_name='item',
            name='recommendation_ranking',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='おすすめ順'),
        ),
        migrations.AddField(
            model_name='itemrecommendation',
            name='recommendation_ranking',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='おすすめ順'),
        ),
        migrations.AddField(
            model_name='tag',
            name='recommendation_ranking',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True, verbose_name='おすすめ順'),
        ),
    ]
