# Generated by Django 2.0.4 on 2018-04-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180426_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='main/img/category', verbose_name='画像'),
        ),
    ]
